# Generated by Django 4.1.6 on 2023-02-11 19:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_geo', '0004_polygons_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
