# Generated by Django 4.1.6 on 2023-02-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0084_staging'),
        ('tenancy', '0009_standardize_description_comments'),
        ('circuits', '0041_standardize_description_comments'),
        ('dcim', '0167_module_status'),
        ('netbox_geo', '0005_alter_point_point'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paths',
            new_name='Path',
        ),
        migrations.RenameModel(
            old_name='Polygons',
            new_name='Polygon',
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'verbose_name': 'Path', 'verbose_name_plural': 'Path'},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Polygon', 'verbose_name_plural': 'Polygon'},
        ),
    ]
