# Generated by Django 4.1.6 on 2023-02-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_geo', '0006_rename_paths_path_rename_polygons_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='geo-import'),
        ),
        migrations.DeleteModel(
            name='geo',
        ),
    ]
