# Generated by Django 4.1.6 on 2023-02-12 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_geo', '0007_path_file_delete_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='file',
        ),
        migrations.AlterField(
            model_name='path',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
